# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: openweather-api
#   description: |
#     [OpenWeatherMap API](https://openweathermap.org/api) provides weather data including current weather, forecasts, and historical data.
#   links:
#     - url: https://github.com/openweathermap
#       title: GitHub Repo
#       icon: github
# spec:
#   type: service
#   lifecycle: experimental
#   owner: team-weather
#   providesApis:
#     - openweather-api

# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: weatherapi-com
#   description: |
#     [WeatherAPI.com](https://www.weatherapi.com/) provides current weather, forecasts, and historical data.
#     This component uses the public API interface.
#   links:
#     - url: https://www.weatherapi.com/docs/
#       title: API Documentation
#       icon: docs
#     - url: https://github.com/weatherapicom
#       title: GitHub
#       icon: github
#     - url: https://api.weatherapi.com/v1/current.json?key=YOUR_KEY&q=London
#       title: Example Request
#       icon: api
#   tags:
#     - weather
#     - api
#     - public
# spec:
#   type: api
#   lifecycle: production
#   owner: team-weather
#   providesApis:
#     - weatherapi-com
#   system: weather-system

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: open-meteo-api
  description: |
    [Open-Meteo](https://open-meteo.com/) provides free weather API with actual 
    [GitHub repositories](https://github.com/open-meteo) available.
  links:
    - url: https://github.com/open-meteo/open-meteo
      title: GitHub Repo
      icon: github
    - url: https://open-meteo.com/en/docs
      title: API Docs
      icon: docs
spec:
  type: api
  lifecycle: production
  owner: team-weather
  system: weather-system
