apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: latestbsdemo
  description: An example of a Backstage application.
  annotations:
    # gitpod.io/host: gitpod.io
    github.com/project-slug: ravalivudutha96/latestbsdemo
  # links:
  #   - url: https://gitpod.io/new/#https://github.com/ravalivudutha96/latestbsdemo
  #     title: Open In Gitpod
  #     icon: dashboard
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: guests
  lifecycle: experimental