---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Musquan
spec:
  memberOf: [guests, team-weather, team-iot]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
# apiVersion: backstage.io/v1alpha1
# kind: Group
# metadata:
#   name: guests
# spec:
#   type: team
#   children: []

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---  
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-weather
spec:
  type: team
  children: []  
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-iot
spec:
  type: team
  children: [] 
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: weather-system
spec:
  owner: team-weather 

